/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface CourseMarketInterface extends utils.Interface {
  functions: {
    "courseCount()": FunctionFragment;
    "courses(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userCourses(address,uint256)": FunctionFragment;
    "web2ToCourseId(string)": FunctionFragment;
    "yiDengToken()": FunctionFragment;
    "purchaseCourse(string)": FunctionFragment;
    "hasCourse(address,string)": FunctionFragment;
    "addCourse(string,string,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "courseCount"
      | "courses"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "userCourses"
      | "web2ToCourseId"
      | "yiDengToken"
      | "purchaseCourse"
      | "hasCourse"
      | "addCourse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "courseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userCourses",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "web2ToCourseId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "yiDengToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCourse",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCourse",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "courseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "web2ToCourseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yiDengToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasCourse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addCourse", data: BytesLike): Result;

  events: {
    "CoursePurchased(address,uint256,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CoursePurchased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface CoursePurchasedEventObject {
  buyer: string;
  courseId: BigNumber;
  web2CourseId: string;
}
export type CoursePurchasedEvent = TypedEvent<
  [string, BigNumber, string],
  CoursePurchasedEventObject
>;

export type CoursePurchasedEventFilter = TypedEventFilter<CoursePurchasedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface CourseMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CourseMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    courseCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: BigNumber;
        isActive: boolean;
        creator: string;
      }
    >;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    web2ToCourseId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    yiDengToken(overrides?: CallOverrides): Promise<[string]>;

    /**
     * 用户通过Web2课程ID购买课程，自动查找对应的链上课程ID
     * 使用web2CourseId购买课程
     * @param web2CourseId Web2平台的课程ID
     */
    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * 检查用户是否已购买课程
     * @param user 用户地址
     * @param web2CourseId Web2平台的课程ID
     */
    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * 添加新课程
     * @param name 课程名称
     * @param price 课程价格(YD代币)
     * @param web2CourseId Web2平台的课程ID
     */
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  courseCount(overrides?: CallOverrides): Promise<BigNumber>;

  courses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean, string] & {
      web2CourseId: string;
      name: string;
      price: BigNumber;
      isActive: boolean;
      creator: string;
    }
  >;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
   */
  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userCourses(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  yiDengToken(overrides?: CallOverrides): Promise<string>;

  /**
   * 用户通过Web2课程ID购买课程，自动查找对应的链上课程ID
   * 使用web2CourseId购买课程
   * @param web2CourseId Web2平台的课程ID
   */
  purchaseCourse(
    web2CourseId: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * 检查用户是否已购买课程
   * @param user 用户地址
   * @param web2CourseId Web2平台的课程ID
   */
  hasCourse(
    user: string,
    web2CourseId: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * 添加新课程
   * @param name 课程名称
   * @param price 课程价格(YD代币)
   * @param web2CourseId Web2平台的课程ID
   */
  addCourse(
    web2CourseId: string,
    name: string,
    price: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    courseCount(overrides?: CallOverrides): Promise<BigNumber>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: BigNumber;
        isActive: boolean;
        creator: string;
      }
    >;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    yiDengToken(overrides?: CallOverrides): Promise<string>;

    /**
     * 用户通过Web2课程ID购买课程，自动查找对应的链上课程ID
     * 使用web2CourseId购买课程
     * @param web2CourseId Web2平台的课程ID
     */
    purchaseCourse(
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * 检查用户是否已购买课程
     * @param user 用户地址
     * @param web2CourseId Web2平台的课程ID
     */
    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * 添加新课程
     * @param name 课程名称
     * @param price 课程价格(YD代币)
     * @param web2CourseId Web2平台的课程ID
     */
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CoursePurchased(address,uint256,string)"(
      buyer?: string | null,
      courseId?: BigNumberish | null,
      web2CourseId?: null
    ): CoursePurchasedEventFilter;
    CoursePurchased(
      buyer?: string | null,
      courseId?: BigNumberish | null,
      web2CourseId?: null
    ): CoursePurchasedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    courseCount(overrides?: CallOverrides): Promise<BigNumber>;

    courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    yiDengToken(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * 用户通过Web2课程ID购买课程，自动查找对应的链上课程ID
     * 使用web2CourseId购买课程
     * @param web2CourseId Web2平台的课程ID
     */
    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * 检查用户是否已购买课程
     * @param user 用户地址
     * @param web2CourseId Web2平台的课程ID
     */
    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * 添加新课程
     * @param name 课程名称
     * @param price 课程价格(YD代币)
     * @param web2CourseId Web2平台的课程ID
     */
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    courseCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    web2ToCourseId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yiDengToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * 用户通过Web2课程ID购买课程，自动查找对应的链上课程ID
     * 使用web2CourseId购买课程
     * @param web2CourseId Web2平台的课程ID
     */
    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * 检查用户是否已购买课程
     * @param user 用户地址
     * @param web2CourseId Web2平台的课程ID
     */
    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * 添加新课程
     * @param name 课程名称
     * @param price 课程价格(YD代币)
     * @param web2CourseId Web2平台的课程ID
     */
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
